
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN M14 [get_ports clk]

#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_read_user[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_in_user[0]}]

#set_property PACKAGE_PIN N20 [get_ports {data_read_user[0]}]
#set_property PACKAGE_PIN P20 [get_ports {data_read_user[1]}]
#set_property PACKAGE_PIN R19 [get_ports {data_read_user[2]}]
#set_property PACKAGE_PIN T20 [get_ports {data_read_user[3]}]
#set_property PACKAGE_PIN T19 [get_ports {data_read_user[4]}]
#set_property PACKAGE_PIN U13 [get_ports {data_read_user[5]}]
#set_property PACKAGE_PIN V20 [get_ports {data_read_user[6]}]
#set_property PACKAGE_PIN W20 [get_ports {data_read_user[7]}]
#set_property PACKAGE_PIN W19 [get_ports {data_read_user[8]}]
#set_property PACKAGE_PIN Y19 [get_ports {data_read_user[9]}]
#set_property PACKAGE_PIN W16 [get_ports {data_read_user[10]}]
#set_property PACKAGE_PIN Y16 [get_ports {data_read_user[11]}]

set_property PACKAGE_PIN R17 [get_ports {data_in_user[0]}]
set_property PACKAGE_PIN U20 [get_ports {data_in_user[1]}]
set_property PACKAGE_PIN R16 [get_ports {data_in_user[2]}]
set_property PACKAGE_PIN N16 [get_ports {data_in_user[3]}]
set_property PACKAGE_PIN R14 [get_ports {data_in_user[4]}]
set_property PACKAGE_PIN P14 [get_ports {data_in_user[5]}]
set_property PACKAGE_PIN L15 [get_ports {data_in_user[6]}]
set_property PACKAGE_PIN M15 [get_ports {data_in_user[7]}]
set_property PACKAGE_PIN T10 [get_ports {data_in_user[8]}]
set_property PACKAGE_PIN T12 [get_ports {data_in_user[9]}]
set_property PACKAGE_PIN T11 [get_ports {data_in_user[10]}]
set_property PACKAGE_PIN T14 [get_ports {data_in_user[11]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]

set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports e]
set_property IOSTANDARD LVCMOS33 [get_ports f]
set_property IOSTANDARD LVCMOS33 [get_ports g]

set_property PACKAGE_PIN K14 [get_ports a]
set_property PACKAGE_PIN H15 [get_ports b]
set_property PACKAGE_PIN J18 [get_ports c]
set_property PACKAGE_PIN J15 [get_ports d]
set_property PACKAGE_PIN M17 [get_ports e]
set_property PACKAGE_PIN J16 [get_ports f]
set_property PACKAGE_PIN H18 [get_ports g]

#set_property PACKAGE_PIN P15 [get_ports MemWrite_user]
#set_property IOSTANDARD LVCMOS33 [get_ports MemWrite_user]

set_property IOSTANDARD LVCMOS33 [get_ports {OPCODE[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPCODE[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPCODE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPCODE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPCODE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {OPCODE[0]}]
set_property PACKAGE_PIN U13 [get_ports {OPCODE[5]}]
set_property PACKAGE_PIN T19 [get_ports {OPCODE[4]}]
set_property PACKAGE_PIN T20 [get_ports {OPCODE[3]}]
set_property PACKAGE_PIN R19 [get_ports {OPCODE[2]}]
set_property PACKAGE_PIN P20 [get_ports {OPCODE[1]}]
set_property PACKAGE_PIN N20 [get_ports {OPCODE[0]}]
