set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports e]
set_property IOSTANDARD LVCMOS33 [get_ports f]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports g]

#set_property IOSTANDARD LVCMOS33 [get_ports clk_rom]
set_property IOSTANDARD LVCMOS33 [get_ports en_rom]


set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN L16 [get_ports {A[3]}]
set_property PACKAGE_PIN M18 [get_ports {A[2]}]
set_property PACKAGE_PIN H17 [get_ports {A[1]}]
set_property PACKAGE_PIN K19 [get_ports {A[0]}]
set_property PACKAGE_PIN K14 [get_ports a]
set_property PACKAGE_PIN H15 [get_ports b]
set_property PACKAGE_PIN J18 [get_ports c]
set_property PACKAGE_PIN J15 [get_ports d]
set_property PACKAGE_PIN M17 [get_ports e]
set_property PACKAGE_PIN J16 [get_ports f]
set_property PACKAGE_PIN H18 [get_ports g]
set_property PACKAGE_PIN H16 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports BT0]
set_property IOSTANDARD LVCMOS33 [get_ports BT1]
set_property IOSTANDARD LVCMOS33 [get_ports BT2]
#set_property IOSTANDARD LVCMOS33 [get_ports pl]
set_property PACKAGE_PIN W14 [get_ports BT0]
set_property PACKAGE_PIN W13 [get_ports BT1]
set_property PACKAGE_PIN P15 [get_ports BT2]
#set_property PACKAGE_PIN M14 [get_ports pl]

#set_property PACKAGE_PIN M14 [get_ports clk_rom]
set_property PACKAGE_PIN M14 [get_ports en_rom]

