set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property IOSTANDARD LVCMOS33 [get_ports in]
set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports pl]
set_property PACKAGE_PIN R17 [get_ports in]
set_property PACKAGE_PIN U20 [get_ports pl]
set_property PACKAGE_PIN N20 [get_ports out]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN R16 [get_ports reset]
set_property PACKAGE_PIN M14 [get_ports clk]
